include_recipe "sprout-osx-base::bash_it"
include_recipe "pivotal_workstation::create_var_chef_cache"
include_recipe "pivotal_workstation::sshd_on"
include_recipe "sprout-osx-apps::skype"
include_recipe "sprout-osx-apps::firefox"
include_recipe "sprout-osx-apps::dropbox"
include_recipe "sprout-osx-apps::chrome"